### ISSUE TITLE
License of `src/ofxJSONElement.*`

### ISSUE THREAD

**Issue by merkys** [jeffcrouse/ofxJSON#29]
Text contents of `src/ofxJSONElement.*` files bear the following copyright indication:
```
 *  Created by Jeffrey Crouse on 12/17/10.
 *  Copyright 2010 Eyebeam. All rights reserved.
```
Eyebeam is not mentioned neither in `license.md` nor in `README.md` thus it is not clear what rights are reserved to that company. In strict sense "All rights reserved" imposes more conservative limitations than MIT license. Could the intention of the cited lines be clarified?

**Comment by jeffcrouse** [comment]
@merkys I apologize for the confusion about the file headers. Those were created automatically by XCode and I failed to remove them. The MIT license should be assumed.

**Comment by merkys** [comment]
Thanks a lot @jeffcrouse!
